### ISSUE TITLE
404 for pre-trained ResNeXt models

### ISSUE THREAD

**Issue by eric-mitchell** [pytorch/hub#252]
I'm currently getting a 404 when following the instructions [here](https://pytorch.org/hub/facebookresearch_WSL-Images_resnext/) for loading the Instagram pre-trained ResNeXt models. It looks like the source repo changed their `master` branch to be `main`, so instead of

    model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl')

one simply needs

    model = torch.hub.load('facebookresearch/WSL-Images:main', 'resnext101_32x8d_wsl')

and all is well.

**Comment by NicolasHug** [comment]
Thanks for the report @eric-mitchell

I believe you're relying on an old torch version (or more accurately, not the latest one), because this is something that we fixed on the latest torch version. Running `model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl')` should work properly in torch >= 1.10, as the default branch assumption was updated to "if main exists use main, else use master".
