### ISSUE TITLE
Add FCOS

### ISSUE THREAD

**Issue by jdsgomes** [pytorch/hub#265]
FCOS model has been recently added to TorchVision, therefore should also be added here

https://github.com/pytorch/vision/pull/4961

**Comment by NicolasHug** [comment]
Thanks for the issue @jdsgomes , would you like to submit a PR?

**Comment by datumbox** [comment]
FCOS uses the C++ ops of TorchVision like nms. I'm not sure we can add it on TorchHub without creating fallback ops in standard PyTorch. 

We know that such fallback ops are likely to be slower than the C++/CUDA equivalents but because these were implemented several years ago, we don't know how much slower they will be. It might be worth benchmarking this on the future and assess if fallback ops is a viable strategy to expose our models via TorchHub. I think for now, we are probably going to close the ticket as nofix?

**Comment by jdsgomes** [comment]
Thanks for raising those important points @datumbox. Closing the ticket.
