### ISSUE TITLE
ImportError: cannot import name 'wide_resnet50_2'

### ISSUE THREAD

**Issue by huangsiyuzhoujie** [pytorch/hub#46]
when i use model = torch.hub.load('pytorch/vision', 'resnext50_32x4d', pretrained=True) and accur error:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-75e761155f91> in <module>
----> 1 model = torch.hub.load('pytorch/vision', 'densenet121', pretrained=True)

/opt/conda/lib/python3.6/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    334     sys.path.insert(0, repo_dir)
    335 
--> 336     hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
    337 
    338     entry = _load_entry_from_hubconf(hub_module, model)

/opt/conda/lib/python3.6/site-packages/torch/hub.py in import_module(name, path)
     68         spec = importlib.util.spec_from_file_location(name, path)
     69         module = importlib.util.module_from_spec(spec)
---> 70         spec.loader.exec_module(module)
     71         return module
     72     elif sys.version_info >= (3, 0):

/opt/conda/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/opt/conda/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.cache/torch/hub/pytorch_vision_master/hubconf.py in <module>
      5 from torchvision.models.densenet import densenet121, densenet169, densenet201, densenet161
      6 from torchvision.models.inception import inception_v3
----> 7 from torchvision.models.resnet import resnet18, resnet34, resnet50, resnet101, resnet152,\
      8     resnext50_32x4d, resnext101_32x8d, wide_resnet50_2, wide_resnet101_2
      9 from torchvision.models.squeezenet import squeezenet1_0, squeezenet1_1

ImportError: cannot import name 'wide_resnet50_2'`

**Comment by ailzhang** [comment]
Hmmm I cannot repro this on my end. Try `model = torch.hub.load('pytorch/vision', 'resnext50_32x4d', pretrained=True, force_reload=True)`?

**Comment by lkhphuc** [comment]
I have the same issue loading ResNext from pytorch hub, I ran on Kaggle kernels and reset multiple time.
However this works fine: `model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl')`

**Comment by ailzhang** [comment]
@lkhphuc Have you tried the `force_reload` I posted above? If it still doesn't work, would you mind posting your python version & pytorch version & torchvision commit in `~/.cache/torch/`? Thanks!

**Comment by lkhphuc** [comment]
Yes, even with `force_reload=True`.
This is easiest to reproduce, you just go on Kaggle and create a new kernel and try it.
![image](https://user-images.githubusercontent.com/12573521/60788790-b290c600-a187-11e9-9cbc-da6687dc9a09.png)

**Comment by szagoruyko** [comment]
I reproduced the issue, it depends if you import torchvision or not.

Case 1:
```python
import torch
model = torch.hub.load('pytorch/vision', 'resnext50_32x4d', pretrained=True)
```
works,

Case 2:
```python
import torch
import torchvision
model = torch.hub.load('pytorch/vision', 'resnext50_32x4d', pretrained=True)
```
does not. The reason is that in Case 1 torchvision is loaded from master, so if you import torchvision after, you will get master torchvision !
In Case 2, torchvision is already imported, so can't be loaded from master, and there is no wide_resnet, it does thus fail.

The behaviour with master torchvision is dangerous actually, can we somehow be more strict?
cc @fmassa

**Comment by awaelchli** [comment]
I have he same issue. The workaround from @szagoruyko works, but in my code it is kind of impossible to do the torch.hub.load before torchvision import. Guess we have to wait for a torchvision update.

**Comment by szagoruyko** [comment]
@awaelchli another workaround is to install master torchvision:
```
pip install git+https://github.com/pytorch/vision
```

**Comment by awaelchli** [comment]
@szagoruyko Oh right. Now I see that I actually misunderstood and thought we are running a too new version of torchvision. It's the other way around. Thank you.

**Comment by ailzhang** [comment]
Thanks @szagoruyko for the detailed repro and workarounds. Yes this is one of the Python caching "feature" that once it has seen a `torchvision` it will just use the cached version forever (in that process). 
I think both workarounds look good to me: 
- call `hub.load` before `import torchvision`
- install master verision of `torchvision`.

In the long term I would love to learn what you want to use from `torchvision` other than the models. And we might want to add those into hubconf so that the import effort can be deduplicated. @awaelchli  @lkhphuc @huangsiyuzhoujie @szagoruyko Thanks!

**Comment by fmassa** [comment]
I had some quick discussion with @szagoruyko , and one possibility for fixing it would be to make `hub` modify the library name to a temporary name, like `_temp_hub_module_ca6f2d` with string substitution, just after cloning the repo.

So it would replace `import torchvision` with `import _temp_hub_module_ca6f2d` in the repo that has been cloned.

This is very hacky, but could be a solution.

**Comment by ailzhang** [comment]
@fmassa renaming the library is pretty hacky and will require some regex to help. 
Imagine the following
```
from torchvision import x
from torchvision.x import y
torchvision_x = blabla
```
It might be error prone to use regex to define where to replace `torchvision` with `_temp_hub_module_ca6f2d` in the code hmmm

**Comment by fmassa** [comment]
@ailzhang it's possible to come up with some heuristics, but it's very hacky indeed.

Also, the solution "call `hub.load` before `import torchvision`" is not a good solution, because it can break user code if there is a breaking change in torchvision.

**Comment by ailzhang** [comment]
@fmassa I feel "installing torchvision from master" shares the same issue if torchvision has breaking changes? 

Now it sounds to me maybe it's better and simpler to add those necessary auxiliary class/functions into hubconf, so that hubconf essentially becomes an API that we promise to BC as much as we can.
- On one hand, hub already support auxiliary 'tokenizer`s etc.
- On the other hand, we used to have the issue that as a python library, user can manage to import whatever internal function we have, and that can be broken easily in new releases. 
What do you think?

**Comment by fmassa** [comment]
The difference is that installing torchvision from master is not transparent from the user: importing a hub model shouldn't change under the hood the version of torchvision that you are using in your script.  If we could have it in a sandbox, it would be better

**Comment by fmassa** [comment]
BTW, @ailzhang from @soumith comment on https://github.com/pytorch/vision/pull/971

> Follow-up tasks wrt torch.hub are:
> 
> - change hubconf.py to make sure:
>    - torchvision is not already loaded into the python session
>    - if it is loaded, the version loaded matches the version being hub-sideloaded -- if not raise a Warning or error

This would indeed fix the problem that has been mentioned in this issue.

**Comment by soumith** [comment]
the root of the problem is that this model definition that is trying to be loaded relies on `torchvision` to be imported. that really shouldn't be the case, the model definitions should be self-contained

**Comment by xianyizhu1024** [comment]
I use this function _torch.hub.load_state_dict_from_url()_ to load pretrained models avoiding the ImportError: cannot import name 'wide_resnet50_2'.

`
import torchvision.models as models
from torchvision.models.resnet import  model_urls

torch.hub.load_state_dict_from_url(model_urls['resnet50'])
 `

**Comment by ivder** [comment]
> @awaelchli another workaround is to install master torchvision:
> 
> ```
> pip install git+https://github.com/pytorch/vision
> ```

it works

**Comment by szagoruyko** [comment]
this can be closed now?
