### ISSUE TITLE
error running pytorch_vision in colab

### ISSUE THREAD

**Issue by mbhoshen** [pytorch/hub#84]
I ran the sample code on colab 
### 
from PIL import Image
from torchvision import transforms
input_image = Image.open(filename)
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
input_tensor = preprocess(input_image)
input_batch = input_tensor.unsqueeze(0) # create a mini-batch as expected by the model

# move the input and model to GPU for speed if available
if torch.cuda.is_available():
    input_batch = input_batch.to('cuda')
    model.to('cuda')

with torch.no_grad():
    output = model(input_batch)
# Tensor of shape 1000, with confidence scores over Imagenet's 1000 classes
print(output[0])
# The output has unnormalized scores. To get probabilities, you can run a softmax on it.
print(torch.nn.functional.softmax(output[0], dim=0))**

and I get the error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-8b26b29157d8> in <module>()
      1 from PIL import Image
----> 2 from torchvision import transforms
      3 input_image = Image.open(filename)
      4 preprocess = transforms.Compose([
      5     transforms.Resize(256),

7 frames
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in _compile_and_register_class(obj, rcb, qualified_name)
   1074 def _compile_and_register_class(obj, rcb, qualified_name):
   1075     ast = get_jit_class_def(obj, obj.__name__)
-> 1076     _jit_script_class_compile(qualified_name, ast, rcb)
   1077     _add_script_class(obj, qualified_name)
   1078 

RuntimeError: class '__torch__.torchvision.models.detection._utils.BalancedPositiveNegativeSampler' already defined. (register_type at /pytorch/torch/csrc/jit/script/compilation_unit.h:166)

Any idea what I did wrong?
I am working on a Windows 10 machine, if it matters

**Comment by alvarobartt** [comment]
Hi @mbhoshen, this is probably not the place to post this kind of issues, you should maybe try posting this on: https://github.com/pytorch/vision/issues as this is the hub repository, not the torchvision one.

Anyway, as a first guess is that you are running different pytorch and torchvision versions, so that those are not compatible. You can refer to this listing where some of the torchvision versions depending on the pytorch version are listed: https://pytorch.org/get-started/previous-versions/

You can also share the pytorch and torchvision version you are using on Google Colab with the following lines' output:

```python
import pytorch
pytorch,__version__

import torchvision
torchvision.__version__
```

Hope this helped you! 👍🏻

**Comment by ailzhang** [comment]
Yup agreed with @alvarobartt that this doesn't look related to hub, I'm going close this via https://github.com/pytorch/hub/issues/84#issuecomment-703464007. Please feel free to open an issue in pytorch/vision instead.

**Comment by alvarobartt** [comment]
Thanks @ailzhang! Glad to be contributing to pytorch somehow 👍🏻
